name: lint
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      with:
        python-version: '3.14.7'
    - name: Install Poetry
      uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8 # v4
      with:
        poetry-version: 1.8.4
    - name: Install dependencies
      run: poetry install
    - name: Check pyproject
      run: poetry check
    - name: Run pre-commit
      run: poetry run pre-commit run --all-files
    - name: Build test image
      run: docker build --target test -t blitzableiter-test .
    - name: Run tests in Docker
      run: docker run --rm blitzableiter-test
'on':
  workflow_call: null
permissions:
  contents: read
