name: lint
jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.14.7'
    - name: Install Poetry
      uses: abatilo/actions-poetry@fd0e6716a0de25ef6ade151b8b53190b0376acfd # v3
      with:
        poetry-version: 1.8.4
    - name: Install dependencies
      run: poetry install
    - name: Check pyproject
      run: poetry check
    - name: Run pre-commit
      run: poetry run pre-commit run --all-files
    - name: Build test image
      run: docker build --target test -t blitzableiter-test .
    - name: Run tests in Docker
      run: docker run --rm blitzableiter-test
'on':
  workflow_call: null
permissions:
  contents: read
